west:
  url: https://github.com/foundriesio/west
  revision: 1980f707d6cb2b71d3488420e928051cc0a9df13
manifest:
  defaults:
    remote: foundriesio
    revision: master
  remotes:
  - name: foundriesio
    url-base: https://github.com/foundriesio
  projects:
  - name: zephyr
    remote: foundriesio
    revision: 90a8a2a1ea051ab20f18518bfdf54b7cb0d63117
    west-commands: scripts/west-commands.yml
  - name: mcuboot
    remote: foundriesio
    revision: 086c9150b7e07d180cf8a1f78a5f78d6a0694d9e
  - name: mbedtls
    remote: foundriesio
    revision: 60fbd5bdf05c223b641677204469b53c2ff39d4e
    path: mcuboot/sim/mcuboot-sys/mbedtls
  - name: tinycbor
    remote: foundriesio
    revision: f5a172b976de07f7bb37d2d24149d6c7a1e512e1
  - name: dm-lwm2m
    remote: foundriesio
    revision: f4ca069703e58a9ba1d996ca25085f0e7338c2ab
    path: zmp-samples/dm-lwm2m
  - name: zephyr_tools
    remote: foundriesio
    revision: 1eb94096f6d4e560beea5fbe13a9ac76490aed58
    west-commands: west-commands.yml
  - name: zmp-container
    remote: foundriesio
    revision: 72868ff0e1e300bd67aed9ba479ce140f91bf9e8
  self:
    path: zmp-manifest
